// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/rag-dashboard/MidnightStudio.tsx": () => import("../components/mockups/rag-dashboard/MidnightStudio.tsx"),
  "./components/mockups/rag-dashboard/QuietMinimal.tsx": () => import("../components/mockups/rag-dashboard/QuietMinimal.tsx"),
  "./components/mockups/rag-dashboard/WarmScientific.tsx": () => import("../components/mockups/rag-dashboard/WarmScientific.tsx")
};
